### ISSUE TITLE
Will jep support the specific python version in the future?

### ISSUE THREAD

**Issue by xsank** [ninia/jep#105]
Now, the jep use the default python version, but we need to use the specific python version in most cases.  
Of course we could set the env to do so, but i recommend adding the env params to jep config so that the sub interpreter could know that immediately.  

By the way, i have tried setting the jvm  env in memory, but for the jep interpreter is being create by the jni and it is sub-process, it is not works.

**Comment by bsteffensmeier** [comment]
Depending on what environmental variables you specifically need to set I think this issue is already covered by #76, #92, and #51. Do you have a recommended enhancement beyond what is in those existing issues?

For the next release of jep, 3.8, I have done some work to try to make Jep slightly smarter about finding and loading native libraries, it is not a complete solution to any of those tickets but I think it is moving the code in the right direction. You can read more about it in the [dev_3.8 release notes](https://github.com/ninia/jep/blob/dev_3.8/release_notes/3.8-notes.rst) or check out the dev_3.8 branch to test it out.

I don't have any plans to take this further in the immediate future and I am not aware of anyone else working this area of jep.

**Comment by xsank** [comment]
@bsteffensmeier thank you for your contribution in your spare time.

**Comment by bsteffensmeier** [comment]
I'm closing this issue as a duplicate because #76, #92, and #51 address the same problem and each have more specific recommendations on what can be done to improve jep.
