### ISSUE TITLE
Scala: Returning an object from Python throws cast exception

### ISSUE THREAD

**Issue by pgschr** [ninia/jep#125]
- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: 3.6.4
- Java Distribution and Version: 1.8

The following Scala code:
```
 class MyClass6 (val x: Int, val y: Int) {}

 val jep = new Jep
 jep.runScript("first.py")
 jep.set("arg6", 2)
 jep.eval("ret6 = retObj(arg6)")
 val result6 = jep.getValue("ret6")
 println(result6)

```
and the script in Python:

```
class MyClass6(object):
    x = 0
    y = 0

def retObj(a):
    mc6 = MyClass6()
    mc6.x = a * 1000
    mc6.y = a * 2000
    return mc6
```
print the following:

> <__main__.MyClass6 object at 0x0000000032BF1DA0>

But when I try to cast `getValue` like so:

`val result6 = jep.getValue("ret6").asInstanceOf[MyClass6]`

I get the following error:

> java.lang.ClassCastException: java.lang.String cannot be cast to test.MyClass6

How to return an object from Python?

**Comment by ndjensen** [comment]
It appears you have MyClass6 defined both in Scala and Python.  Therefore when you call the constructor in Python `mc6 = MyClass6()` you create a Python MyClass6 since you didn't import the Java/Scala one.  In the current versions of Jep you can't return a Python object to Java/Scala.  Jep will attempt to auto-convert common Python objects like primitives, strings, lists, and dictionaries to Java equivalents, but the fallback behavior is to return the `str()` version of the Python object (which is less than ideal but it's been the behavior in Jep for years).  In short, you can't get a Python object out of `getValue(String)` unless Jep has already coded the conversion.  We are looking at returning Python objects (or at least pointers to them) to Java for Jep 4.0 but that is experimental and not guaranteed.

I'm not quite sure what you're aiming for, but if you just have the Java/Scala class, in the Python you should be able to do `from fullyQualifiedPackageName import MyClass6` and you'll have the Java/Scala class wrapped in a Python object.  So remove the Python definition of MyClass6, in Python import the Java/Scala version, and then the rest of your code should work.

**Comment by pgschr** [comment]
Thanks for the advise. Following your comments, this works:

Scala
```
  jep.set("arg6", 2)
  jep.eval("ret6 = retObj(arg6)")
  val result6 = jep.getValue("ret6").asInstanceOf[MyClass6]
  println("x="+result6.x, "y="+result6.y )

```
Python
```
from test import MyClass6
def retObj(a):
    mc6 = MyClass6(7,8)
    return mc6
```
But if I change the function in Python assigning class members, it doesn't work:

```
from test import MyClass6
def retObj(a):
    mc6 = MyClass6(7,8)
    mc6.x = a * 1000
    mc6.y = a * 2000
    return mc6
```

I get the following error in `mc6.x = a * 1000` 

> <class 'TypeError'>: Not a pyjfield object.

What is this error?

**Comment by pgschr** [comment]
This problem is similar to my previous question (both throw the same error), the difference is that in the previous question the class was instantiated in Scala, and in the current question the class is instantiated in Python. In both cases, the class member assignment seem to be not possible.

**Comment by bsteffensmeier** [comment]
It does not matter where the class is instantiated. Your scala class does not have a public field x so you cannot assign to the field x in python.

**Comment by ndjensen** [comment]
Related to #124.
