### ISSUE TITLE
Dynamically load of python scripts in Java from String

### ISSUE THREAD

**Issue by aitorhh** [ninia/jep#131]
Looking at the API from Jep in Java, I've realized that it's not possible to load dynamically a script from a string. Of course, there are multiple alternatives to accomplished this:
1. As #55 suggested, use `eval('exec _pythonScript')`
2. Write temporal files to disk
3. Wrap the script as a function, and use `invoke()` if function was previously loaded. How?
4. Provide a `runScript(InputStream)` or `runScript(String code)` with the code.

I believe that the last options could improve the performance since to interactive mode is required. What is the best way to accomplish this?

**Comment by ndjensen** [comment]
I'd consider this a duplicate of #55 and perhaps we should shift discussion over there.  The question there is how to go forward with the public API to make it handle developers' use cases while being easy to understand.  My understanding is that `runScript(String)` was originally added to support running `jep someFile.py` from the command line against a script, just like `python someFile.py`.  So for the purposes of the public API, I'm not sure we should keep the name `runScript` for the method that you're trying to accomplish.  I also don't think we should accept an InputStream because we can't stream that to Python (though I haven't fully researched it) so Jep would just be reading the stream into a String anyway.

You don't need to wrap a script in a function, you just need to make it a single "statement".  [Here is an old example](https://github.com/Unidata/awips2-core/blob/unidata_17.1.1/common/com.raytheon.uf.common.python/src/com/raytheon/uf/common/python/PythonInterpreter.java#L50) with wrapping methods in a function, and [here is an example](https://github.com/Unidata/awips2-core/blob/unidata_17.1.1/common/com.raytheon.uf.common.python/src/com/raytheon/uf/common/python/PythonInterpreter.java#L50) with using a while loop or try/except block.  Those are based on an earlier version of Jep, but you get the idea.

**Comment by aitorhh** [comment]
Great! After your comments I will continue with the solution provided at #55. It's the one I have running at the moment and until I evaluate the performance I will leave it there :)

Thanks!
