### ISSUE TITLE
[request] change NamingConventionClassEnquirer's addTopLevelPackageName() to return itself

### ISSUE THREAD

**Issue by tropicalpb** [ninia/jep#144]
In order wrap the entire Jep in an autocloseable and still able to pass in custom top level package name

try (Jep jep = new Jep(new JepConfig().setClassEnquirer(
      new NamingConventionClassEnquirer().addTopLevelPackageName(...)
    ))){
} catch (...) 

thanks

**Comment by ndjensen** [comment]
I have mixed feelings about this.  You can create the `ClassEnquirer` on a line above and get it setup before adding it to the `JepConfig` and the `try-with-resources` block.  Even then the `JepConfig` setup could be on a line above the `try-with-resources` too.  That might make code more readable instead of chaining everything together in a single line.  Also you could write your own `ClassEnquirer`.  I'm undecided.

**Comment by ndjensen** [comment]
After thinking about this more, I agree with this idea to make it more convenient.  You can make a pull request on the dev_3.9 branch or I will get to it sooner or later for the next release.

**Comment by ndjensen** [comment]
This has been fixed at https://github.com/ninia/jep/commit/832ed0c0985c7c8df3e4e25f96ef152efc076736 in preparation for release 3.9.

**Comment by bsteffensmeier** [comment]
Jep 3.9.0 has been released.
