### ISSUE TITLE
Question regarding multithreading

### ISSUE THREAD

**Issue by soerenGer** [ninia/jep#146]
- Windows 10, x64
- Python 3.6.6
- JDK 1.8.0_171

We just stated to use JEP in naivly, when we stumbled quite early about the fact, that a JEP instance cannot be used from multiple threads once instantiated. The scenario is quite simple:

- A stand alone server makes use of a Python lib which is very costly in terms of computing time and memory to create and initilize
- Therefore we need to have it in memory until the JVM process itself is shutdown
- It is created in the main thread but should be used via an REST interface (server by Jetty) which obviously has it's own threads -> BANG!

My approach would be simply to have a singleton around the JEP instance and route all calls through "synchronized" methods of the singleton. Due to the underlying problem we can anyhow create only a single instance of this library so this would be a perfect fit. But, this does not work with JEP, so what could be solutions:

1. Fork JEP and remove the checks in Jep.isValidThread() to return always true. I have done some work with JNI already and would not confirm that multithreading and JNI in general is a problem (as the JEP doc suggessts). This however is the most dirty solution...
2. Wrap the single instance into a threaded on it's own and talk to it using a wrapper and RMI internally. Would work, but still somwhow crude.
3.  I read something about the "shared modules feature", which could solve the problem somehow on Python level. But I was not able to find an example or more description of it, so don't know how to use this. However, just from reading some basic information about it this could be a nice fit as the "one global Python lib instance" is exactly what we requrire and I could still guarantee that only a single thread will access the JEP environment.

The preferred order for solving this would likely be 3, 2, 1, so where can I learn something about this shared module feature and how is it applied.

Best regards,
Soeren

**Comment by bsteffensmeier** [comment]
> Fork JEP and remove the checks in Jep.isValidThread() to return always true. I have done some work with JNI already and would not confirm that multithreading and JNI in general is a problem (as the JEP doc suggessts). This however is the most dirty solution...
1. JNI is not the limit on threading, Python is. Python internally has thread local variables tracking the PyThreadState and if you don't handle this exactly right you will crash, so you would need significant changes to the Jep data structure and interaction with the python library to make this work, if it is even possible.
> Wrap the single instance into a threaded on it's own and talk to it using a wrapper and RMI internally. Would work, but still somwhow crude.
2. I believe this is the most common approach, I'm not sure what you had in mind but you can easily integrate basic java multithreading datastructures like Queues, Callables and Futures to pass the data between threads.
> I read something about the "shared modules feature", which could solve the problem somehow on Python level. But I was not able to find an example or more description of it, so don't know how to use this. However, just from reading some basic information about it this could be a nice fit as the "one global Python lib instance" is exactly what we require and I could still guarantee that only a single thread will access the JEP environment.
3. Using shared modules should work. It was not really designed for this use case so I don't know of anyone else using it this way but there is no technical reason it shouldn't work. You would just need to put everything you are sharing in a python module and set your JepConfig to share that module and then any classes, functions, and objects within that module would be shared. For some libraries it can be complicated getting shared modules working so if you are using Jep 3.8 you might consider a [SharedInterpreter](http://ninia.github.io/jep/javadoc/3.8/jep/SharedInterpreter.html) instead of Jep with shared modules.

**Comment by RunsLikeADeere** [comment]
I did some multi-threading tests which led me to create a Jep-Thread Pool in Java and used by the parent Java program.  It is a common requirement that a given thread maintain its defined Python-side variables, imports, config, shared modules, etc. over a thread's "session" with Python.  It turned out the implementation was straight-forward.  Also, success with the share modules--so thanks for the work on that.

**Comment by soerenGer** [comment]
Okay, thank you very much for your answers! We tried the shared modules feature with our Python code and it seems to work, gladly ;-) As we are using dedupe and numpy in the background we need some more tests, but this feature looks promising. On further problems we will also try the 3.8 with SharedInterpreter first as recommended.

Thanks a lot, Sören
