### ISSUE TITLE
Sporadically python output is redirected to java console

### ISSUE THREAD

**Issue by pacher** [ninia/jep#151]
- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: Anaconda 5.2.0, Python 3.6.5 :: Anaconda, Inc.
- Java Distribution and Version: java 10.0.2 2018-07-17
- Jep Version: 3.8.1
- Python packages used (e.g. numpy, pandas, tensorflow): numpy

Minimal code example to reproduce an issue:
```java
import jep.Jep;
import jep.JepConfig;
import jep.JepException;

public class JepOutputIssue {
    public static void main(String[] args) throws JepException {
        Jep jep = new JepConfig()
                .setRedirectOutputStreams(false)
                .setInteractive(false)
                .createJep();
        jep.eval("import numpy as np");

        //Works fine if repeated 122 times or less
        for (int i = 0; i < 123; i++) {
            jep.eval("a = np.eye(3, 3)");
            jep.eval("b = np.eye(3, 3)");
            jep.eval("np.dot(a, b)");
        }

        System.out.println("done");
    }
}
```
If the `for` loop above repeated for 122 time or less, then only "done" is printed to console, as expected. However if repeated for 123 times or more, then lots of
```
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```
messages (result of last expression) are dumped to console, just like when output is redirected by `setRedirectOutputStreams(true)`

The exact number of iterations when it happens depends on what python code is doing. But is the same for the same code. In my working code it happens after 10. For the example above it is 122 on my machine. Unfortunately I don't have a possibility to try on different OS/machine at the moment.

My current workaround is to assign the result of last expression to dummy variable which is never read, i.e. change `np.dot(a, b)` to `r = np.dot(a, b)` in the example above.

Anyway, this behavior is really strange and since I spent some time to nail it down to small code snippet, I decided to submit this bug report. Maybe you have some clue on what's going on.

Please feel free to close this issue if it is too weird or hard to reproduce.

**Comment by bsteffensmeier** [comment]
I can explain what is happening, but I'm not really sure exactly what we should be doing different.

First `jep.eval()` is using `Py_single_input`, which means if the expression evaluates to an object then it will be printed. I'm not a big fan of this behavior but I think the interactive jep interpreter is relying on it.

With `setRedirectOutputStreams(false)` the python output will just go to stdout. If you don't change your Java `System.out` then usually Python and Java are printing to the same place. When I try to reproduce your issue on the command line then I always see all the `array(...)` output for each iteration of the loop. When I redirect the output to a file then I see your issue, although the cutoff for me is 112 times through the loop. The issue is that internally python is buffering the output, when it detects a terminal then it is line buffered so all the output gets flushed as long as it ends in newline, but when I redirect to a file then it is using an 8k buffer so it only flushes if I write more than 8k. It appears when you close jep that we just discard any buffered output. I am guessing that you are running in an IDE or some other environment that is doing some redirection of stdout that causes python to switch to the 8k buffer mode. I was not able to repeat this on python 2, it always prints everything. I looked at the python source and I didn't pinpoint the exact change but it is obvious they shuffled around much of the related logic.

As I mentioned I'm not sure what we should do, a few different things that occurred to me;
1) On `Jep.close()` we could flush sys.stdout to ensure that the buffer is not lost. This would result in always seeing the output. We should also update the javadoc on `Jep.eval()` to indicate that it prints the result.
2) If Jep is not interactive then perhaps we should not be printing the result of `jep.eval()`, which we could do if we stop using `Py_single_input`. I think this is more inline with what you want and I think it makes sense, however I am worried that one of the other modes would have other subtle differences that would make it harder to debug through the interactive interpreter so need to do more research.
3) We could expose the eval mode, either as a method arg or by providing alternative methods that use different modes. This could be similar to the python builtin [compile](https://docs.python.org/3/library/functions.html#compile) perhaps? We could probably knock out #55 if we did this well.

**Comment by bsteffensmeier** [comment]
interactive mode has been deprecated in change 8b856a5 for 3.9. The plan is to remove interactive mode in 4.0 which should resolve this issue.

**Comment by pacher** [comment]
First, thanks for the explanation and sorry for the late reply :-)
It was really counter-intuitive and maybe should be documented somewhere. Because with setRedirectOutputStreams(false) I was expecting to have no output, like `>> null` or something for python. Otherwise why would this option exist? Now I see that java output could be redirected itself and the option is there for that case :) But it is not immediately obvious.

From the user point of view I would expect
1) An option to disable python std output (what I thought redirect(false) would do). In case I need to execute in a loop some chatty script from a colleague
2) Better yet to have an option to provide my own stream to jep/python or some other means to read python std output from java. This way I can analyze it, integrate with logging systems etc. I could just dump it to strdout myself or shut the python up by using no-op stream or similar.
The problem is though how to deal with not consumed output, we can not just buffer everything and blocking also does not sound like a good idea...

**Comment by bsteffensmeier** [comment]
All of those options can be controlled by the developer by modifying sys.stdout in the python interpreter, you can discard output or funnel it into a Java object or even callback into Java whenever output is written. Rather than try to anticipate everyones needs and provide methods in jep I think it is better to expose the python interpreter and leave it to developers to build layers on top of jep that meet their specific needs.

**Comment by lfcnassif** [comment]
Hi, first thank you for this great library!

I had success to redirect my python script stderr/stdout prints to java configured logger, but messages from tensorflow-2.4 are still being printed to console. Any workaround to redirect tensorflow messages too?
