### ISSUE TITLE
Trouble running Jep from Java on Windows 10

### ISSUE THREAD

**Issue by fearofcode** [ninia/jep#157]
- OS Platform, Distribution, and Version: Windows 10 x64, Version 1803
- Python Distribution and Version: 3.7.0
- Java Distribution and Version: 10.0.2
- Jep Version: 3.8.2 (latest master as of 19 August 2018, d1c7f1479ae46893fdab45c34088e1d788609b09)
- Python packages used (e.g. numpy, pandas, tensorflow): None

I have the following Java code in my project:

```Java
package org.wkh.arete;

import jep.Jep;
import jep.JepException;

public class JepTest {
    public static void main(String[] args) throws JepException {
        try(Jep jep = new Jep()) {
            jep.eval("print('hello world from jep')");
        }
    }
}
```

As you may have guessed, I was hoping the interpreted code would print `hello world from jep` to stdout and exit without error.

When I run this code, I get the following stack trace:

```
Exception in thread "main" jep.JepException: <class 'ImportError'>: dynamic module does not define module export function (PyInit_jep)
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)
	at jep.Jep.configureInterpreter(Jep.java:276)
	at jep.Jep.<init>(Jep.java:256)
	at jep.Jep.<init>(Jep.java:228)
	at jep.Jep.<init>(Jep.java:140)
	at org.wkh.arete.JepTest.main(JepTest.java:8)
```

I may have done something wrong, because to even get to this I had to manually copy files from `site-packages/jep` to my JDK bin directory. Before doing that, I got an error saying jep was not in the `java.library.path`.

When you Google that exception message, what comes back is errors where someone mixes up Python 2 and Python 3. I don't have Python 2 installed on this machine so I'm not sure if that's what's somehow happening here.

Any ideas on what I should try? Thanks!

**Comment by fearofcode** [comment]
Yes, I did. That page is where the trouble began. https://landinghub.visualstudio.com/visual-cpp-build-tools gives a 404 so I had to try to download the build tools separately. I tried both the 2015 and 2017 build tools and neither seems to offer installation of 14.1. If you install 2015, it just gives you 14.0. I I went through several install/uninstall cycles.

I wound up with both when I eventually got something that would build.

**Comment by ndjensen** [comment]
[This page](https://www.scivision.co/python-windows-visual-c++-14-required/) has working links and indicates that Python 3.7 requires MSVC 14.

[You need to remove the .pyd file](https://github.com/ninia/jep/wiki/Windows#other-insights) since you have both the .pyd and the .dll.

When you got the error about jep not being in java.library.path you might have had a good dll and just needed to [set some Java arguments or environment variables](https://github.com/ninia/jep/wiki/FAQ#how-do-i-fix-unsatisfied-link-error-no-jep-in-javalibrarypath).

You should try the Jep mailing list instead of a github issue as your questions will be seen by more users of Jep,

**Comment by fearofcode** [comment]
After deleting the .pyd file, it works! Thanks.
