### ISSUE TITLE
Is jep correct solution for my problem?

### ISSUE THREAD

**Issue by Mahesha999** [ninia/jep#158]
I want to call some python scripts from java by sending some data to them and also receive back some return values from python scripts. Currently I am sending the scripts and the input data as json string along with some metadata to python and obtaining the output of python scripts along with some metadata in java by communicating over tcp sockets. I am currently using pandas and numpy in my python script and handled the communication of pandas and numpy objects through json sent to / from java and python.

Earlier I evaluated various options I had in [this stackoverflow post](https://stackoverflow.com/questions/39410339/different-better-approaches-for-calling-python-function-from-java). I wasnt aware of jep at that time.

The requirements I explained in that thread are as follows:

- Call to python script from java should be transparent, in the sense that it should not require modifying `.py` file simply to enable it to be called from java. I might be given any python file with some functions inside it. I should be able to call any of these functions without requiring to modify `.py` file.
- I want to be able to send arguments of both primitive types (`int`, `String`, `floats` etc.) or non primitive types (`HashMap`,`ArrayList`) from java to python function and receive back the returned object (which may of primitive types or non-primitive types) from python to java. I am also using pandas DataFrame and numpy ndarray and hence also want to be able to send and receive corresponding objects to and from java and python.
- I *preferably* want to stick to CPython instead of Jython because I might need to use newer libraries that might not be available in Jython.

Ar these requirements are met jep?  I find following reasons for which jep is unsuitable for my requirements:
- jep does not allow python objects returned back to java (I might be grossly wrong here as I have not tried using Jep yet)
- creating sending and receiving pandas dataframe between java and python is not possible 

Am I right with this?

**Comment by bsteffensmeier** [comment]
Please only report issues that you believe are bugs or feature requests.
Questions about Jep should be directed to the
[mailing list](https://groups.google.com/forum/#!forum/jep-project).

Jep seems like a good fit for your needs. Jep does support getting java objects back from python, [this table](http://ninia.github.io/jep/javadoc/3.8/jep/Jep.html#getValue-java.lang.String-java.lang.Class-) in the javadoc is the most concise summary of the default conversions. For more complex objects such as pandas frames you could use [PyObject](http://ninia.github.io/jep/javadoc/3.8/jep/python/PyObject.html) from Java, or you could write some glue code that would convert the python object into a java equivalent, since jep lets you import java classes into Python it is fairly easy to write a Python function that can convert objects between representations in each langauge. I don't know anything about pandas, but if it supports duck typing then it may be possible to pass java objects directly into pandas without conversion if they match the interface pandas is expecting. I would expect any of these options would be faster than doing a json conversion since there is no intermediary representation between python and java.
