### ISSUE TITLE
Building libjep.so, libjep.jnilib and jep.dll on the same system

### ISSUE THREAD

**Issue by Tatsukyo** [ninia/jep#171]
Hi,

I'm currently trying to use JEP in my project, but even if i'm using Window, my project must can be used on Linux or Mac OS X,

It's look like when i try to install Jep with python setup.py build install or pip install jep

I get only the dll, is there a way to get the so and jnilib ?

Thank u in advance, ur project is greatfull

**Comment by ndjensen** [comment]
The only way to build the Linux libjep.so and macOS libjep.jnlib is to build on those operating systems.  There's not a way to build for different platforms.  If you don't have machines with those OSes available, you could look for some free virtual machines.

**Comment by Tatsukyo** [comment]
well that is sad, can't we just update the setup and his files to get all files? I'm not used to python but i don't get it, it should not require pc component to build right? so why does we need a Linux or MacOS to get the libjep.jnlib ou libjep.so.

Oh and if the Window is a 32-bits is the dll the same as a 64bits ? 

Thanks Anyway, that would be sad if i cannot use Jep in my project

**Comment by ndjensen** [comment]
CPython is written in C and needs to be compiled for the operating system you're using.  For example, you can't take a CPython install for Windows and install it to Linux or macOS.  Jep is the same way, since it is mostly written in C and it calls into the CPython API the native library needs to be compiled for the platform it will run on.  You can reuse the jar on any platform but not the native library.

The dll is not the same for 32-bit vs 64-bit.  Again, this is because it's native code.  Jep no longer supports 32-bit but it might work.  You should compile Jep with the same number of bits as your Python is compiled with, otherwise it won't work.
