### ISSUE TITLE
How I can get the x result and the picture of plt.bar

### ISSUE THREAD

**Issue by dombine** [ninia/jep#175]
the run scripts is dynamic and can not get result with jep.getValue 
![image](https://user-images.githubusercontent.com/29190329/49844326-6e119780-fdfd-11e8-8a29-1e9c7db9993e.png)

**Comment by pedro-roberto** [comment]
Isn't `plt.show()` missing? I can plot with jep, just as I do with regular python.

**Comment by ndjensen** [comment]
I don't understand what you're trying to do.  If you use jep.getValue(String) then it will only work with a limited number of Python types as specified in the wiki here: https://github.com/ninia/jep/wiki/How-Jep-Works#objects  Otherwise, you need to write some custom conversion code in Python to turn it into a Java object.  Many others have used matplotlib successfully, though I don't think they are returning an image object to Java.
