### ISSUE TITLE
Crashing when trying to load AllenNLP model in Flink RichMapFunctiion 

### ISSUE THREAD

**Issue by isaacmg** [ninia/jep#176]
- OS Platform, Distribution, and Version:
Mac OS X 10.13.6
- Python Distribution and Version:
Python 3.7.1 Anaconda 
- Java Distribution and Version:
JDK 8 
- Jep Version: 
From maven 
```
               <dependency>
                <groupId>black.ninia</groupId>
                <artifactId>jep</artifactId>
                <version>3.8.2</version>
            </dependency>
```
- Python packages used (e.g. numpy, pandas, tensorflow):
AllenNLP 
numpy 
pytorch 

Error message 
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000127b9eb70, pid=1508, tid=0x0000000000006603
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libpython3.7m.dylib+0x75b70]  PyModule_GetState+0x0
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```
Code 

```java 
import org.apache.flink.api.common.functions.MapFunction;
import org.apache.flink.api.common.functions.RichMapFunction;
public class predictMap extends RichMapFunction<TweetData, String>{
    @Override
    public String map(TweetData s) throws jep.JepException {
        JepConfig config = new JepConfig();
        config.addIncludePaths("src/python");
        config.addSharedModules("numpy");
        config.addSharedModules("allennlp");
        config.addSharedModules("scipy");
        config.addSharedModules("torch");
        Jep theJep = config.createJep();


        // jep


        //theJep.runScript("src/python/new_test.py");

        theJep.eval("from new_pred import NewTest");
        theJep.eval("s = NewTest()");
        theJep.set("text", s.tweetText); 
}
}
```
Python code 
```python
import allennlp
import os
from allennlp.predictors.predictor import Predictor
from allennlp.models.archival import Archive, load_archive
import logging 
class NewTest():
    def __init__(self):
        self.predictor = Predictor.from_path("src/python/models/model2.tar.gz")
    
    def run(self, text):
        return self.predictor.predict(sentence=text)
```
It fails on the  `theJep.eval("s = NewTest()");` line

**Comment by isaacmg** [comment]
[Full log file can be found here](https://gist.github.com/isaacmg/3291cf3f4b192428e73eb8d38e96fb17)

**Comment by bsteffensmeier** [comment]
The most likely cause is that one of the packages you are using is not fully compatible with sub-interpreters or shared modules. To test for this I recommend Using SharedInterpreter instead of a Jep instance and see if that works better. Since SharedInterpreter does not have an include path, you will need to modify sys.path in python instead.

There is too much going on in your python libraries for me to figure out the cause from the log, can you attempt to isolate the problem more. For example I noticed that [Predictor.from_path](https://github.com/allenai/allennlp/blob/master/allennlp/predictors/predictor.py#L107) is just calling load_archive and Predictor.from_archive, can you split those two calls out in your python and determine which one of the two is crashing? Keep breaking it down until you reach something in the python standard library or until one of the libraries is executing native code.

**Comment by ndjensen** [comment]
Any progress on this, @isaacmg?  Did you try SharedInterpreter instead of SubInterpreter?  Did you try @bsteffensmeier's suggestion to try and narrow down what call is crashing?

**Comment by isaacmg** [comment]
@ndjensen  Yes I was able to get I working with the SharedInterpreter see https://github.com/isaacmg/dl_java_stream
