### ISSUE TITLE
Jep installation is getting failed on Windows

### ISSUE THREAD

**Issue by rmiryala** [ninia/jep#189]
- OS Platform, Distribution, and Version: Windows 7 Professinal
- Python Distribution and Version:python 3.7.3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
- Java Distribution and Version: JDK 1.8
- Jep Version: latest (pip install jep)
- Python packages used (e.g. numpy, pandas, tensorflow): numpy  and pandas
[output.log](https://github.com/ninia/jep/files/3146653/output.log)

Trying out JEP on windows and failing due to above issue. Enclosed the log details

**Comment by ndjensen** [comment]
Your underlying error is

`mt.exe -nologo -manifest build\temp.win-amd64-3.7\Release\src\main\c\Jep\jep.cp37-win_amd64.pyd.manifest -outputresource:build\lib.win-amd64-3.7\jep\jep.cp37-win_amd64.pyd;2
    error: command 'mt.exe' failed: No such file or directory`

You need to figure out why it can't find mt.exe on your system.  Did you follow the instructions here?  https://github.com/ninia/jep/wiki/Windows#python-35-and-36-msvc-build-setup  That says 3.5 and 3.6 but something similar should apply for 3.7.  mt.exe appears to come as part of an SDK and you're probably missing that piece of an SDK or not running the build with that SDK in the environment.  Make sure you're using the SDK Command Prompt instead of the normal Command Prompt.

**Comment by rmiryala** [comment]
@ndjensen Thanks for comment..Yes I followed the above link for installing Jep but i got stuck with above error. After going through the error in detail I understood mt.exe is available as part of SDK as you said. After installing SDK, I am able to install JEP sucessfully.

**Comment by rmiryala** [comment]
@ndjensen Started trying out JEP and as part of that trying to call enclosed python script from Java using Jep.runScript() and it is ending up with core dump.

[TestScript.txt](https://github.com/ninia/jep/files/3152062/TestScript.txt)
[hs_err_pid11820.log](https://github.com/ninia/jep/files/3152066/hs_err_pid11820.log)

Could you please help me in resolving this. 
Is there any blog to post my questions related to JEP

**Comment by bsteffensmeier** [comment]
I recommend using [SharedInterpreter](http://ninia.github.io/jep/javadoc/3.8/jep/SharedInterpreter.html) instead of a regular Jep instance. You can see the wiki page on [cpython extensions](https://github.com/ninia/jep/wiki/Workarounds-for-CPython-Extensions) for more details on this type of issue.

Questions about Jep that are not bugs or efatures should be directed to the
[mailing list](https://groups.google.com/forum/#!forum/jep-project).

**Comment by ndjensen** [comment]
The crash is in numpy which is a CPython extension.  As @bsteffensmeier says, use SharedInterpreter or use Jep's shared modules with numpy and sklearn as shared modules.  SharedInterpreter is the better choice if it works for you.

**Comment by rmiryala** [comment]
@ndjensen This is not an issue and i got the answer from you from mailing list.Hence closing the issue.
