### ISSUE TITLE
Java field of type Map with Integer as key all values in python are lost

### ISSUE THREAD

**Issue by nfalco79** [ninia/jep#190]
Hi we are updating from jep 3.5.2 to 3.8.2 (using python 3.4.3 for Windows)

We have some Java bean that have field of type Map<Integer, Float>. When these object are converted by jep into python object all values in the map are set to None.

```
public class SimpleResult {
    private Map<Integer, Float> integerFloatMap;

    public Map<Integer, Float> getIntegerFloatMap() {
        return integerFloatMap;
    }
    public void setIntegerFloatMap(Map<Integer, Float> integerFloatMap) {
        this.integerFloatMap = integerFloatMap;
    }
}
```

If I change the Map key type from Integer to Long or Float anything else it works.

**Comment by bsteffensmeier** [comment]
I don't think there is anything we can do about this. The method signature for Map.get() takes an Object. When you pass a Python Int into that Java method jep will try to convert it into any Java Object, a Java Long is the most compatible Java class for a Python Int so it is converted to a Long. Since the keys are Integers nothing is found for the Long you passed in.

If we changed the default conversion for Python Int to go to a Java Integer instead then it would fix your issue but then you could not have a Java map with Long keys and that is just as bad so I do not think it is a good fix.

If you know the key is always an Integer then you can modify your Python code to make a Java Integer before passing it into Map.get().

```
        Map<Integer,Float> test = new HashMap<>();
        test.put(1,1.0f);
        try (Jep jep = new Jep(new JepConfig())){
            jep.set("test", test);
            jep.eval("print(test.get(1))"); // prints None
            jep.eval("from java.lang import Integer");
            jep.eval("print(test.get(Integer(1)))"); // prints 1.0
        } catch (JepException e) {
            e.printStackTrace();
        }
```

**Comment by nfalco79** [comment]
we had patch our code that map Jep PyObject to our structure with a utility function like this:
```
if type(key) is int and java_obj.get(key) is None:
    key = Integer(key)
```
