### ISSUE TITLE
Load Jep and Java in Blender 3D

### ISSUE THREAD

**Issue by ansorre** [ninia/jep#195]
Is there anybody who tried to load Jep and Java in a program that already embeds python as its scripting language? Specifically I'm thinking of Blender 3D here. Java also can be embedded in native applications, after all. Any experience to share?

**Comment by bsteffensmeier** [comment]
Jep is a project for embedding a Python interpreter in an existing Java application. Since Blender 3D is not a Java application I don't think Jep would be able to start inside Blender 3D. To embed Java within Python you would need to make significant changes to Jep, although alot of the convenient converter functionality would be reusable. You may have better luck with projects that already access Java from Python such as [Py4J](https://www.py4j.org/).
