### ISSUE TITLE
pyspark jep.JepException: <class 'ModuleNotFoundError'>: No module named 'py4j.protocol'

### ISSUE THREAD

**Issue by glfox** [ninia/jep#196]
- OS Platform, Distribution, and Version: MacOS Mojave, 10.14.5 
- Python Distribution and Version: 3.7.4
- Java Distribution and Version: jdk 1.8.0_191, scala 2.12
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow): pyspark

I was trying to running the following code in scala, simply import the pyspark.
```
val jep = new Jep()
try {
  jep.eval("import pyspark")
} catch {
  case e: Exception => e.printStackTrace()
} finally {
  jep.close()
}
```
Exception:
jep.JepException: <class 'ModuleNotFoundError'>: No module named 'py4j.protocol'
	at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyspark/context.<module>(context.py:29)
	at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyspark/__init__.<module>(__init__.py:51)
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)

I tried the same thing by using the jep command line, and it works.
I installed jep by pip, and also configured LD_LIBRARY_PATH="${PYTHON_HOME}/lib:${LD_LIBRARY_PATH}"
Both pyspark and py4j are in the path.

Any idea?

**Comment by bsteffensmeier** [comment]
I suspect that in your application you have the py4j jar on the classpath but it is not on the classpath of the jep command line. Jep has a Java importer that allows you to directly import Java classes into python, however when a Java package and a Python package have the same name it will ignore the Python package. So when pyspark is internally trying to import py4j it is getting a Java package from Jep instead of the Python package you installed. You could verify this by importing py4j directly and calling dir on that module, I suspect you will not see things like 'protocol' which is in the python package but you will see things like 'reflection' from the Java package.

If this is your problem then to get around it you will need to provide your own implementation of [ClassEnquirer](http://ninia.github.io/jep/javadoc/3.8/jep/ClassEnquirer.html) that returns false when isJavaPackage is called with py4j. You can pass the ClassEnquirer to a JepConfig when creating your Jep instance and this will prevent the import from using the Java pacakge.

I should also mention that I don't think Py4J works in Jep. Both Py4J and Jep are interacting with the C-API for both langauages and will set up conflicting environments for the two languages to interact.

**Comment by glfox** [comment]
You are right. Spark package includes py4j. Thank you!

**Comment by NavodPeiris** [comment]
there is a way to avoid this error and it is explained well in this article:
https://medium.com/@navodPeiris/how-to-run-pyspark-code-from-scala-spark-application-f5c5592c2872

**Comment by NavodPeiris** [comment]
pull request #548 should solve this issue
