### ISSUE TITLE
JepScriptEngine deprecated

### ISSUE THREAD

**Issue by lewiswilliam** [ninia/jep#211]
Hi all,

JepScriptEngine is deprecated in version 3.8.x. What are the other options we have if we are using this in our project?

Regards
William

**Comment by bsteffensmeier** [comment]
There is currently no one actively involved with this project that is familiar with JepScriptEngineFactory or the javax.script API. When we changed the repository layout in 3.8 we noticed that the service file wasn't even included in the build. Since it had been broken for several releases we suspected no one was using the code. To confirm that suspicious we deprecated it in 3.8 to give users a chance to voice any concern and when we got no feedback it was removed from 3.9.

I have not used the javax.script API, is there something you need to use it for that you could not accomplished by using the other Jep APIs?

**Comment by ndjensen** [comment]
In addition to @bsteffensmeier's explanation for why, I don't think we should resurrect it.  In Java 9+ the Java modularity would require the java.scripting module and Jep aims to be as lightweight as possible.  Also, since the code is open source, you could take the old `jep.JepScriptEngine` and `jep.JepScriptEngineFactory` and just repackage them as `org.myorg.JepScriptEngine` and `org.myorg.JepScriptEngineFactory`.  It's just a wrapper around Jep that meets the `javax.script` API.
