### ISSUE TITLE
jep running time overhead

### ISSUE THREAD

**Issue by zoltansx** [ninia/jep#215]
I have python script that runs numerical analysis using numpy/scipy heavily.
For a test I embedded the script into a single Java class, opening a JEP SharedInterpreter, calling a single python function where 
 * the parameters are an array of 700 Integers, an array of ~700 Doubles and a few constants.
 * result is an array of ~20 numbers (mix of Doubles and Integers).

My problem is that embedding the python code into JEP will take it complete in twice as much time (mean time, for ~60000 runs)
For the native run I use the very same python function to run the code as in JEP. Also with this solution I tried to minimize the interaction and the object shared between Java and python.  

I've even moved the measuring start and end times for each run to the python part as I suspected it's not the Java - Jep - python bridge where the time is wasted.

I can't share the actual code with you (and I admit that's a blocker here), still: could you give some advice about where to look for the bottleneck? Or what kind of code/excerpt could I share to shed some light. Or is it some JEP issue? 

Environment:

 * Ubuntu 18.04.3 LTS
 * Python 3.6.8 ( installed with sudo apt-get install python3)
 * OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
 * jep-3.9.0. ( installed with pip3 install jep)
 * Python packages used (numpy, scipy):

**Comment by bsteffensmeier** [comment]
I recommend looking at what types of Java objects you are passing into Python. Some objects are just wrapped Java objects so when you access them in Python it calls back into JNI. For example if you are passing an Integer[] that will be a jarray in python and whenever your code accesses an array element from Python it requires JNI for the array access and conversion to Python int type. If you pass an int[] instead the access will be slightly faster because there is no unboxing of Integer objects. Even faster than an int[] would be to use a [jep.NDArray](http://ninia.github.io/jep/javadoc/3.9/jep/NDArray.html) this still requires copying the data into a python NDArray but the copy happens all at once instead of happening for each element access. The fastest way to share data is [jep.DirectNDArray](http://ninia.github.io/jep/javadoc/3.9/jep/DirectNDArray.html), which uses a direct java buffer so no memory needs to be copied at all.

If you can share any code showing how you copy data in I might be able to provide more insight into how it is represented in python and ways to optimize it.

**Comment by zoltansx** [comment]
In my case a simple python lists is expected for both the integer and double case and adding a print statement to python code showed me that the first item of both lists are int and float python types, i.e. the root cause must be something else.
To go on, I try to come up with some meaningful sample code.

**Comment by zoltansx** [comment]
Update: it looks like it wasn't the elements in the list, but the list itself ( jep.PyJList ).
I added two list comprehensions to at the beginning of the python code to replace the jep.PyJList with python list and it's now much closer to the non-Jep python run times. 
I think we can close this case with these findings - thanks a lot ...
