### ISSUE TITLE
jep production references?

### ISSUE THREAD

**Issue by zoltansx** [ninia/jep#217]
[wiki/Performance-Considerations](https://github.com/ninia/jep/wiki/Performance-Considerations) page says that "Jep is used on production systems that run significant amounts of Python in servers aiming for 99.999% uptime. In these situations there are some recommended best practices."

Just out of curiosity: Is there an actual list of these production deployments what environment they're running and what load jep can handle there?

Jep works fine in a test environment but it would be nice or reassuring to see others already using it in prod.

**Comment by ndjensen** [comment]
The project I was formerly associated with used it in production on both servers and workstations.  It is used by NOAA's National Weather Service for mission critical systems.

Jep is not that much code and is hopefully easy to read if you're interested in exploring it deeper.  It is just the glue between Java and CPython and does not really do heavy lifting.  The danger is mostly in the CPython libraries that a project uses and how well that CPython library was written for a Python embedded environment.  Jep itself has been free of memory leaks and invalid memory accesses (i.e. crashes) since 3.6 if I remember correctly.  Therefore, it theoretically should be safe to run indefinitely, but like any open source software, it is provided as is and there is no guarantee or warranty.

Otherwise, we are a small project and are unaware of how developers and companies are using Jep.  It would be great to receive feedback, but I don't know how to elicit that kind of feedback.  If you know how to elicit that feedback, please help.

**Comment by zoltansx** [comment]
It looks that github does/cannot give you any means for that.
Running google search for the term " ninia/jep -site:github.com/ninia/jep " resulted in the following:

An article using JEP for OpenML Python:
https://medium.com/feedzaitech/supporting-python-with-feedzai-openml-engine-577de61cebe3

A guide to "a language to express Parametric Trace Properties":
http://vasco.imag.fr/tools/partrap/PartrapUserGuide.html

Some thread tagged with #data-science :
https://clojurians-log.clojureverse.org/data-science/2018-01-13

So not too much.

**Comment by RBerkheimer** [comment]
Hi @ndjensen - Just curious who uses it at NWS. I've been following JEP for a while and looking at using it for the python connector of a polyglot workflow system at NOAA NCEI, that's primarily written in clojure. If there are already groups using it here it would help with our case for security.

**Comment by ndjensen** [comment]
@RBerkheimer, the AWIPS II system used at WFOs and NCEP.  You can find most of the source on Unidata's github page.  Most (all?) of Jep used by that system has a layer wrapped around it, https://github.com/Unidata/awips2-core/tree/unidata_18.1.1/common/com.raytheon.uf.common.python/src/com/raytheon/uf/common/python.  A lot of that code was written prior to Jep 3.

**Comment by RBerkheimer** [comment]
That's great and extremely helpful. Glad to get this news! Many thanks.

**Comment by ndjensen** [comment]
Just found Jep is used by polynote.
https://polynote.org/docs/03-mixing-programming-languages.html
https://github.com/polynote/polynote

**Comment by 313hemant313** [comment]
[WrapPyJ](https://github.com/313hemant313/wrappyj) - Auto‑generate Java wrappers for any Python library — seamless, zero‑glue interoperability.
