### ISSUE TITLE
support for javafx?

### ISSUE THREAD

**Issue by berryma4** [ninia/jep#24]
for example:

``` python
from javafx.application import Application
from javafx.scene import Scene
from javafx.scene.layout import AnchorPane


class Hello(Application):
    def start(self, stage):
        stage.setTitle("Hello, World!")
        root = AnchorPane()
        scene = Scene(root, 100, 40)
        stage.setScene(scene)

        stage.show()

if __name__ == '__main__':
    Application.launch(Hello().class, [])
```

**Comment by ndjensen** [comment]
Probably two separate things here.
* Javafx itself.  Swing works so in theory javafx will work but I haven't tried it.  There's a small amount of swing code in [Run.java](https://github.com/mrj0/jep/blob/master/src/jep/Run.java) so that may need to be updated for javafx.  Also I don't see javafx in the [classlist_8.txt](https://github.com/mrj0/jep/blob/master/src/jep/classlist_8.txt) file so the default ClassList may not load those classes and it may be a bit trickier to test and experiment with.
* The other issue is implied from your example code.  You have Python class Hello extending Java class Application.  Jep doesn't support cross-language inheritance at this time, and it'd be quite a leap forward to develop that.  It'd be cool to have that support, but we need to achieve some more attainable goals first.  The closest thing to that that Jep supports is you can have a Python object implement a Java interface.

So I think javafx will run in Jep though we may need to make a few minor modifications.  And at this time you'd need to define your Application extension in Java and then you could import and manipulate it from Python.

**Comment by bsteffensmeier** [comment]
It is not clear what would need to be done to support javafx better and there are currently no plans to investigate this ticket further so I consider it out of scope of jep.
