### ISSUE TITLE
SubInterpreter breaks with unittest

### ISSUE THREAD

**Issue by cbcmg** [ninia/jep#245]
This may fall into the "known issues with extensions" bucket, but I would be interested in any ideas to workaround it. I've provided a sample project which aborts with SIGSEGV every time on my computer.  In short, the code simply performs "import unittest" in two subsequent SubInterpreter() invocations, closing the first before calling the second. The second time, it core dumps. From the stack, it might be a problem with the asyncio module. But as this is a Python distributed library, I would have thought it should avoid any issues with using sub-interpreters (global variables, etc.). Thanks for any input!

[jepbug.zip](https://github.com/ninia/jep/files/4543813/jepbug.zip)

macOS: 10.13
JRE version: OpenJDK Runtime Environment (13.0.2+8) (build 13.0.2+8)
Java VM: OpenJDK 64-Bit Server VM (13.0.2+8, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
Python brew-installed 3.8.2 (and in a debug build of 3.8.1 installed by pyenv)
Running from a "venv" virtual environment

Top of the stack (in the 3.8.1 debug build):

Stack: [0x0000700009241000,0x0000700009341000],  sp=0x00007000092f7b70,  free space=730k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [_asyncio.cpython-38d-darwin.so+0x1dfd]  _Py_INCREF+0x1d
C  [_asyncio.cpython-38d-darwin.so+0x1754]  PyInit__asyncio+0x1f4
C  [jep.cpython-38d-darwin.so+0x258222]  _PyImport_LoadDynamicModuleWithSpec+0x312
C  [jep.cpython-38d-darwin.so+0x257b2a]  _imp_create_dynamic_impl+0x16a
C  [jep.cpython-38d-darwin.so+0x256f34]  _imp_create_dynamic+0xa4

Background:
I've put jep into a custom gradle plugin to build a custom set of python sources/templates/etc. The gradle plugin lives in a long running gradle daemon. Among other tasks, I want to use test frameworks (unittest, pytest) to run python tests as part of the gradle build lifecycle. I've tried using SharedInterpreter but that does seem to share too much state (e.g. requiring me to reload() python modules) and makes consecutive runs non-determinant.

**Comment by cbcmg** [comment]
Digging through unittest, it is indeed asyncio causing the sef fault.

Commenting out this import from unittest.__init__.py which in turn imports asyncio,  and the crash is gone.

# from .async_case import IsolatedAsyncioTestCase

**Comment by bsteffensmeier** [comment]
Unfortunately even within the cpython standard modules there is not great support for sub-interpreters. We have had problems before with the datetime module. The only solution within jep is to set the shared modules in JepConfig to reuse whatever modules cannot be used in multiple interpreters. In this case I would try adding "_asyncio" to the shared modules, since that is the native portion of asyncio, sharing that should prevent the crash and share is little state as possible.

This looks like it may actually be resolved with [Python issue 40294](https://bugs.python.org/issue40294). If that is the case upgrading to a nightly version of 3.8 or downgrading to python 3.7 should resolve the issue.

**Comment by cbcmg** [comment]
Thanks for the feedback. Adding _asyncio to shared modules has resolved the issue. And thanks for the pointer to the fix in the cpython; amazing timing :) Cheers for the great tool!

**Comment by bsteffensmeier** [comment]
This was a bug in cpython that has been resolved.
