### ISSUE TITLE
PyObject.setAttr shall declare JepException

### ISSUE THREAD

**Issue by Reissner** [ninia/jep#247]
**Describe the bug**
Im not so much into jni but it seems as if PyObject.setAttr is based on 
Java_jep_python_PyObject_setAttr defined in jep_object.c. 
obviously, this throws JepException but this is not declared in setAttr. 
Isn't this wrong?? 

And by the way: is there no check in the toolchain so that this is discovered? 

Now i saw the same issue in PyObject.delAttr, equals, toString and hashCode. 

I am not sure what no thread objects available means... 
If i use the Jep, i would like to know of course. 

**To Reproduce**
Include a small Java class with a main method that produces the error or a specific sequence of commands that can be run from the jep [interactive console](https://github.com/ninia/jep/wiki/Interactive-Console). If your problem involves a specific Python module then please indicate if it is possible for you to import that module from the jep interactive console.

**Expected behavior**

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version:
- Python Distribution and Version:
- Java Distribution and Version:
- Jep Version:
- Python packages used (e.g. numpy, pandas, tensorflow):

**Additional context**

**Comment by ndjensen** [comment]
I don't know how we would detect that the native method is missing a throws declaration.  

Regarding `equals(Object)`, `toString()`, and `hashCode()`, we cannot change the method signature since those methods are overriding super class methods.  Regarding `delAttr(long, long, String)` and `setAttr(long, long, String, Object)`, since those are private native methods and the public method already throws the exception it will be transparent to a developer using Jep.  Please submit a pull request on the dev_3.9 branch that corrects those two.

**Comment by ndjensen** [comment]
Fixed on dev_3.9 branch targeted for 3.9.1 release.
