### ISSUE TITLE
Less exceptions, some runtime exceptions, all exceptions documented. 

### ISSUE THREAD

**Issue by Reissner** [ninia/jep#249]
**Is your feature request related to a problem? Please describe.**
I feel that Jep throws too many checked exceptions. 
as even execution throws an exception, one cannot use jep without enclosing in a try contstruct. 
I know other integrations with less exceptions. 
Also JepException well.. its name is tied on a product. 
That should not be, it should be specific for the problem. 
E.G. in one case a null argument yields a JepException. 
Normally it is a NullArgumentException (apache) or just an IllegalArgument. 
Also, there is no documentation: just written `if an error occurs`, .. well not very specific. 
Also in one case, a JepException covers an IOException... is this a good idea? 

I started an analysis and found one and the same exception can have many roots, 
even in a single method! This should not be. 

I think the problem is very diverse and so is the solution. 
For example: `THROW_JEP(env, "Couldn't get thread objects.");` 
Well, i must understand what this means and then react on that exception. 
But there is no documentation and in c i am so weak, i dont really understand. 
How can it be that i could not get thread objects? 
If i have that exception: what shall i do? 

**Describe the solution you'd like**
I analyzed where the exceptions come from and as it is not a single problem, 
there cannot be a single solution. 
What i can describe here is just a process to come to a solution. 
I did analysis already. I would like to create a new branch and show to you. 
It turns out that there are various categories of situations which throw JepException. 
The solution is specific for each category. 
Solution can be, 
- documentation, 
- avoiding exception 
- transforming into JepRuntimeException (unchecked) 
- other exception (IllegalArgumentException, IOExeption)

I have also an idea, when we know, that we resolved the problem: 
For each method declaring checked exception, it shall be clearly documented 
when the exception occurs and how to avoid it.

**Comment by bsteffensmeier** [comment]
We are already planning to switch JepException to extend RuntimeException, however since that would break API it is planned for a major version increment, see #202 

Most Jep calls involve calling arbitrary Python statements that can throw any Python exception so it is impossible to know what went wrong, if any exception is thrown from Python it will result in a JepException. We have some ideas to allow you to access the source Python Exception from a JepException however it is complicated so is not available yet.

There are many places where another exception may be more appropriate, in your example about thread state I believe that is impossible to hit so an IllegalStateException is probably more appropriate. Many times jep exceptions are thrown simply because they are more convenient.

**Comment by ndjensen** [comment]
Exceptions have been changed on dev_4.0 branch here: https://github.com/ninia/jep/commit/a06d949f2d5036234fdd30efc89540410868151c

**Comment by ndjensen** [comment]
Closing as @bsteffensmeier pointed out, you could get any Python exception from Python so JepException is inherently broad and covers all Python.  And JepException is now an unchecked exception with Jep 4.0.
