### ISSUE TITLE
Fatal python error on building SharedInterpreter

### ISSUE THREAD

**Issue by austinv11** [ninia/jep#254]
**Describe the bug**
Upon instantiating SharedInterpreter, a fatal error shuts down java. It is reported as:
```
Fatal Python error: PyCOND_INIT(gil->cond) failed
Python runtime state: preinitialized

Current thread 0x00007fa347d8b700 (most recent call first):
<no Python frame>
```

**To Reproduce**
I am able to 100% reproduce by running `jep` in my environment. It should be noted that I am running jep in a docker container.

**Expected behavior**
No fatal error

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version (within docker): Alpine Linux v3.11
- Python Distribution and Version: CPython 3.8
- Java Distribution and Version: OpenJDK 13
- Jep Version: 3.9.0
- Python packages used (e.g. numpy, pandas, tensorflow): numpy

**Additional context**
Here is the Dockerfile definition of the container
```Dockerfile
FROM adoptopenjdk/openjdk13:jdk-13.0.2_8-alpine

ENV PYTHONUNBUFFERED=1

RUN apk --no-cache add curl gcc g++

# Taken from: https://github.com/Docker-Hub-frolvlad/docker-alpine-python3/blob/master/Dockerfile
RUN echo "**** install Python ****" && \
    apk add --no-cache python3-dev&& \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    \
    echo "**** install pip ****" && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --no-cache --upgrade pip setuptools wheel && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi

RUN apk --no-cache add py3-numpy
RUN pip install jep

WORKDIR /javaapp/

ENV PYTHONPATH /usr/lib/python3.8/site-packages
```

**Comment by bsteffensmeier** [comment]
Your Java and Python libraries where built using different and incompatible versions of libc and I don't think there is anything we can do in jep to make the two work nicely together. The Java installed in that docker image is using glibc while the python and jep are using musl libc and based off the answer to [this stack overflow question](https://stackoverflow.com/questions/60342622/am-i-chasing-ghosts-dynamically-linked-libraries-in-glibc-exe-on-muslc-environm) I do not think they can work correctly together. You will probably need to rebuild either Java or Python and Jep so that all the pieces are using the same libc versions.

I don't think it will be very helpful but I will include the details of what I found in case anyone has other ideas. We leave jep [here](https://github.com/ninia/jep/blob/v3.9.0/src/main/c/Jep/pyembed.c#L408). The source of the error in python code is failure in [pthread_cond_init](https://github.com/python/cpython/blob/v3.8.2/Python/thread_pthread.h#L147). Python does not print the return code so I modified jep to call pthread_cond_init and found it is returning EINVAL, the problem seems to be related to CLOCK_MONOTONIC, when I just use a NULL attribute the call succeeds.  From what I can tell pthread_cond_init() in alpine is provided by the musl libraries but I [don't see any way that could possibly fail](https://git.musl-libc.org/cgit/musl/tree/src/thread/pthread_cond_init.c). Looking at the way the various libraries are linked:

```
/ # ldd /usr/lib/python3.8/site-packages/jep/libjep.so 
	/lib/ld-musl-x86_64.so.1 (0x7f66aa57a000)
Error loading shared library libjvm.so: No such file or directory (needed by /usr/lib/python3.8/site-packages/jep/libjep.so)
	libpython3.8.so.1.0 => /usr/lib/libpython3.8.so.1.0 (0x7f66aa293000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f66aa57a000)
Error relocating /usr/lib/python3.8/site-packages/jep/libjep.so: JNI_GetCreatedJavaVMs: symbol not found
/ # ldd /usr/lib/libpython3.8.so.1.0
	/lib/ld-musl-x86_64.so.1 (0x7f054d54e000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f054d54e000)
/ # ldd /opt/java/openjdk/bin/java
	/lib64/ld-linux-x86-64.so.2 (0x7fee4102c000)
	libz.so.1 => /lib/libz.so.1 (0x7fee41012000)
	libjli.so => /opt/java/openjdk/bin/../lib/libjli.so (0x7fee40e01000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fee4102c000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fee4102c000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fee4102c000)
Error relocating /opt/java/openjdk/bin/../lib/libjli.so: __strdup: symbol not found
Error relocating /opt/java/openjdk/bin/../lib/libjli.so: __rawmemchr: symbol not found
```

It seems odd that java and python have different libc implementations, I modified jep to report the address of pthread_cond_init at runtime and it is using the version from /usr/glibc-compat/lib/ld-linux-x86-64.so.2(/lib64/ld-linux-x86-64.so.2 is a symbolic link to the same file). When python is running normally that library isn't even loaded so it would use a different version of pthread_cond_init. I think both libraries are provided by musl so I'm not sure why there is different behaviour but since this type of mixed environment is not well supported in current versions of musl I don't think we can expect it to work.

**Comment by austinv11** [comment]
Ah, thanks for investigating this! It makes sense that it doesn't work then. I assumed java would be built with musl too since that's standard for most alpine packages. But that is obviously not the case. Feel free to close this ticket since supporting this environment is probably not worth the effort. I will try varying my Docker environment to make libc implementations match.

**Comment by andyczerwonka** [comment]
@austinv11 What base image did you end up with to make this work? [I'm seeing the same problem](https://github.com/scalapy/scalapy/issues/269) in my attempt to invoke `Python` inside my `alpine`-based container.

**Comment by austinv11** [comment]
@andyczerwonka It's been awhile but I believe I just moved to a ubuntu-based container instead (not ideal, I know).

**Comment by andyczerwonka** [comment]
> @andyczerwonka It's been awhile but I believe I just moved to a ubuntu-based container instead (not ideal, I know).

I **think** the only answer is `don't use Alpine`, but that's a larger scope change that I'd like to find an alternative to. E.g. maybe use a `Python` base image and `ADD` a JRE.
