### ISSUE TITLE
compiling jep with native image

### ISSUE THREAD

**Issue by zcaudate** [ninia/jep#271]
I'm having issues compiling jep with graalvm -> currently using the jdk11 version.

The program compiles okay but when I run the program and it tries to create a SharedInterpreter, it gives this error:

```
╰─$ target/ex11-jep
WARNING: Failed to get and cache frequent class types!
WARNING: Failed to get and cache primitive class types!
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: [Z
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:326)
        at jep.Jep.init(Jep.java)
        at jep.Jep.<init>(Jep.java:278)
        at jep.SharedInterpreter.<init>(SharedInterpreter.java:56)
```

I'm not sure if it's an issue with graal, jep or my native image settings and would be thankful for any pointers

```
:opts     ["--report-unsupported-elements-at-runtime"
                            "--initialize-at-build-time"
                            "--allow-incomplete-classpath"
                            "--no-server"]}
```

**Comment by bsteffensmeier** [comment]
I am not very familiar with graal but based off the response to [your graal ticket](https://github.com/oracle/graal/issues/2660) you will need to provide a jniconfig file with information about every class the jep uses through JNI. To figure out what jep uses internally you can start with the classes we cache in [jep_util.h](https://github.com/ninia/jep/blob/master/src/main/c/Include/jep_util.h#L105). Unfortunately whenever you access a java object from python Jep is using JNI to access the class and methods you use so you would need to include every java class you use in your own python in the jniconfig for graal as well. This will greatly decrease your flexibility to use java objects in python and depending on your use case may make it difficult to use jep with graal.

If you do get even a partially working configuration for graal please post it in a reply to this ticekt so that others who are using graal can use it also.

**Comment by zcaudate** [comment]
@bsteffensmeier: I've created a sample repo here that compiles a jar, instruments and generates the config files and then builds the image. However, once the image is built I'm getting a [strange output ](
https://github.com/oracle/graal/issues/2724)

It'd be great if I can get some help looking at how to get around this issue because I feel like  the build pathway is quite close to being realised.

**Comment by bsteffensmeier** [comment]
You could try writing a different ClassEnquirer and using it with your JepConfig, the ClassList is usually good for most people but since you have to specify any classes you are loading with JNI before compiling you probably need a more limited set of classes available to python anyway.

**Comment by zcaudate** [comment]
I don't know that it would solve the problem. I had another version where I was manually mapping out the ClassList in `java_access/` and got lots of `Not Found` errors but got to the same stage as using the agent.

I'm pretty positive the jni-config that was generated by running the agent mapped out all the jni classes. I just had to include native array classes in another config.

What does the ClassEnquirer do?

**Comment by zcaudate** [comment]
it'd be great if you can try running the sample repo. It's relatively straight forward and I'm hoping you might have a couple more insights that I might be missing.

**Comment by bsteffensmeier** [comment]
The [ClassEnquirer](http://ninia.github.io/jep/javadoc/3.9/jep/ClassEnquirer.html) determines which python import statements should be handled by loading java classes.

I mention it because jep.ClassList is on your stack trace calling Package.getPackages() which is failing in graal so it seems you need to fix graal for that, however if you implement your own ClassEnquirer that never calls Package.getPackages() then surely you would not get this same error.

**Comment by zcaudate** [comment]
okay. I see the line that's it's failing at. I'm not too familiar with Jep internals or Package.getPackages(). What would happen if these packages are not loaded?

**Comment by zcaudate** [comment]
Apparantly it's fixed in Graal: https://github.com/oracle/graal/pull/1027
