### ISSUE TITLE
HowTo close, then open a new jep instance

### ISSUE THREAD

**Issue by ericmandm** [ninia/jep#273]
Hello,
I am trying to implement a 'reset' feature for my app, which includes killing the existing 'connection' to the jep-connected resource and then re-creating the jep connection.  So far, I have not been successful.  I thought that closing the existing interpreter would allow me to create a new one.

As an example, the below code crashes outside the JVM...
The first block that creates the pyInterpreter works fine and I can execute python statements normally.
When I close pyInterpreter and create a new one (subInterpreter2), the first .eval statement crashes it.

```
            // the python module has a class called 'Camera'
            pyInterpreter = jepConfig.createSubInterpreter();
            pyInterpreter.eval("import basler_python_proxy as cam_proxy");
            pyInterpreter.eval("instance = cam_proxy.Camera()");
            pyInterpreter.eval(null);   // flush the statement buffer
            pyObject = pyInterpreter.getValue("instance", PyObject.class);

            pyInterpreter.close();

            SubInterpreter subInterpreter2 = jepConfig.createSubInterpreter();
            subInterpreter2.eval("import basler_python_proxy as cam_proxy");   // crashes the app outside the JVM
            subInterpreter2.eval("instance = cam_proxy.Camera()");
            subInterpreter2.eval(null);   // flush the statement buffer
            PyObject pyObject2 = pyInterpreter.getValue("instance", PyObject.class);

```
What is the correct process for terminating one interpreter and creating a new one to replace it?

Thanks!

**Comment by bsteffensmeier** [comment]
Some python modules are not compatible with sub-interpreters and will cause crashes when used in sub-interpreters. [SharedInterpreter](http://ninia.github.io/jep/javadoc/3.9/jep/SharedInterpreter.html) works much better in these cases and should prevent the crash.

If you require the isolation of sub-interpreters then you could instead try setting up [shared modules](http://ninia.github.io/jep/javadoc/3.9/jep/JepConfig.html#addSharedModules-java.lang.String...-) to include the python modules which are not compatible with sub-interpreters, although it can be difficult to properly set that up because it can also require sharing other dependencies or internal modules.

**Comment by ericmandm** [comment]
Awesome.  A SharedInterpreter allows me to close it, then open a new one and eval new statements without crashing.
Thanks!
