### ISSUE TITLE
First instanciation of SharedInterpreter runs endlessly

### ISSUE THREAD

**Issue by FeelLemon** [ninia/jep#274]
I am trying to use Jep in the software on which I'm working, developed on Eclipse with OSGi.
I managed to install jep, load it and load all the dlls, by setting environment variables like Path and PYTHONHOME. Here is the code I'm trying to run (it's just an example, to test if jep works) : 
```
try (Interpreter interp = new SharedInterpreter()) {
        System.out.println("On est rentré dans jep");
	interp.exec("from java.lang import System");
	interp.exec("s = 'Hello World'");
	interp.exec("System.out.println(s)");
	interp.exec("print(s)");
	interp.exec("print(s[1:-1])");
} catch (JepException e) {
	e.printStackTrace();
```
The problem I have is that the execution is stuck at the first line, the instanciation of SharedInterpreter, endlessly.
After digging into the sources, and inserting some `throw` or `exit()` code in java sources or C sources and recompiling jep each time, I managed to see where this endless execution problem comes from.
It is in pyembed.c, in the method pyembed_startup, and the problem is the call to `Py_Initialize()`.
Indeed, if I put an `exit()` just before, my execution crashes, and if I put it just after, it never stops.

My main problem is that I have no Error or Exception that could help me understand what's happening, just an endless execution.
And the weirdest part is that if I try to run this code outside of my software, on a simple Java project, everything works. So it means that my installation of jep and python are fine. Maybe the problem comes from the fact that my software uses OSGi as it's the main difference, but I don't really know.
I saw [here](https://github.com/ninia/jep/wiki/FAQ) that jep is supposed to work with OSGi. Do you have an example of a use of jepp in an OSGi environment?

I don't know if you'll be able to help me on this, but I try, we never know.

**Environment:**
- OS Platform, Distribution, and Version: Windows 10, 64bit
- Python Distribution and Version: Python 3.8.2 (standard CPython distribution) - 64bit
- Java Distribution and Version: JavaSE-1.8
- Jep Version: 3.9.0
- Python packages used (e.g. numpy, pandas, tensorflow): numpy installed

**Comment by bsteffensmeier** [comment]
It looks to me like you are suffering from [this python bug]( https://bugs.python.org/issue39345) and the closed bug it links to has a ton of information that I haven't had time to read through yet.

For OSGi the problems have to do with getting the correct classloader and finding java classes. This would occur way after the spot where you are freezing so I suspect your current problem is not OSGi related. If you get past this it is likely that you will have to implement your own [ClassEnquirer](http://ninia.github.io/jep/javadoc/3.9/jep/ClassEnquirer.html) to help Jep figure out what Java classes can be loaded.

Since that python bug has to do with the stdio streams I suspect your application framework is setting those up differently than a regular java application so if there is anyway to control the way your framework is handling stdio you may be able to work around it that way, but I am just guessing.

**Comment by FeelLemon** [comment]
Thanks a lot for the quick reply!
You're probably right, and this issue you linked seems quite accurate for my case, I will take a look at it.
I will also try to run my code on linux (my application is also on linux) to see if the problem is only happening on Windows.
