### ISSUE TITLE
JVM crashes if SharedInterpreter is re-intialized

### ISSUE THREAD

**Issue by NeverStopDrowning** [ninia/jep#294]
I am running Java application (active all the time but not executing anything till it gets a wakeup signal) which has to create JAVA object every execution (when a wake up signal arrives), this object initializes new SharedInterpreter to execute Python ML libraries. This works perfectly fine the first execution after initializing the application, but the next execution JVM crashes.

I debugged that a while, in the second run,  jep.so library is already loaded, Java thread which initialized python still there (state moved from RUNNING to WAITING) however JAVA object created all this, is gone !
Creating new Java object will try to initialize new SharedInterpreter, consequently will try to reload jep.so which is not allowed.

I am really stuck !

**Comment by bsteffensmeier** [comment]
Do you have a Java stack trace, from an exception or from an hs_err file? If you can get a stack trace it might help determine what is going wrong.

It's possible your ML library does not support multithreading. I would recommend running the same code but just execute some simple python instead of the ML code to verify the rest of the code is working correctly.

If you can create a simple program that demonstrates the error and post it here then I could try to run it and debug further into jep to help find what is going on.

**Comment by NeverStopDrowning** [comment]
Thanks for the reply !
Well, that is the first thing I tried, I used a simple python script to print "Hello World" and actually the crash happens while initializing a new interpreter from JAVA through...  
SharedInterpreter newObj = new SharedInterpreter();

Attached the crash log. 
[vm_crash.log](https://github.com/ninia/jep/files/5414513/vm_crash.log)

I placed also some debug messages in JEP
Thread Name: JobDispatcher ID: 58 
Initializing new SharedInterpreter
Java Thread  
JEP_CORE: Constructor of Jep()
JEP_CORE: Inside getMainInterpreter()
JEP_CORE: Inside getMainInterpreter() and instance is NULL
JEP_CORE: Inside MainInterpreter::initialize and getting closer
JEP_CORE: Inside MainInterpreter::initialize and Jeb.so is loaded ? true
JEP_CORE: Inside MainInterpreter::initialize and after Jeb.so loading trial
JEP_CORE: Inside MainInterpreter::initialize and before intializing python
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f570b3463a6, pid=64038, tid=0x00007f55610f6700
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6993a6]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by bsteffensmeier** [comment]
I see, since you already created one interpreter successfully it should not be possible to get into MainInterpreter.initialize() because the MainInterpreter is already set up and as you have noted it is still running. The only way I can imagine this is possible if your application has two different ClassLoaders that are both loading the MainInterpreter class and each trying to intialize it. If this is the case it is not surprising that python is crashing. Unfortunatly I do not think there is any way we could allow jep to work from two different ClassLoaders.

**Comment by NeverStopDrowning** [comment]
Thanks so much for the support !
