### ISSUE TITLE
jep.JepException: <class 'TypeError'>: iter() returned non-iterator of type 'jep.PyJIterable'

### ISSUE THREAD

**Issue by mike-hunhoff** [ninia/jep#307]
`Jep` throws `jep.JepException: <class 'TypeError'>: iter() returned non-iterator of type 'jep.PyJIterable'` when Python attempts to iterate a Java object that implements both `Iterator` and `Iterable`.

The cause appears to be the following code:

https://github.com/ninia/jep/blob/8a2746a2ff67d219d76733f05d526e4c65e9a177/src/main/c/Jep/convert_j2p.c#L194-L203

`Jep` first checks if a Java object is assignable from `Iterable`, and then checks if the object is assignable from `Iterator`. `Jep` therefore defaults to `jep.PyJIterable` when wrapping a Java object that implements both `Iterable` and `Iterator`. The `iterator()` method of the Java class in question returns a reference to itself, which after `Jep`s conversion is an object of type `jep.PyJIterable`. This causes the aforementioned exception when attempting to iterate the Java object in Python.

I have had success fixing this issue by making the following changes to `convert_j2p.c#L194-L203`:

```
if ((*env)->IsAssignableFrom(env, class, JITERABLE_TYPE)) {
        if ((*env)->IsAssignableFrom(env, class, JITERATOR_TYPE)) {
            result = PyJIterator_Wrap(env, jobj, class);
        } else{
            if ((*env)->IsAssignableFrom(env, class, JCOLLECTION_TYPE)) {
                if ((*env)->IsAssignableFrom(env, class, JLIST_TYPE)) {
                    result = PyJList_Wrap(env, jobj, class);
                } else {
                    result = PyJCollection_Wrap(env, jobj, class);
                }
            } else {
                result = PyJIterable_Wrap(env, jobj, class);
            }
        }
```

Essentially these changes give priority to `jep.PyJIterator` when wrapping a Java object that implements both `Iterable` and `Iterator`.

I am a very interested to hear your thoughts on this issue and the proposed fix. Thank you!

OS: `Ubuntu`
Python: `Python 3.8.5`
JDK: `openjdk 11.0.9.1`

**Comment by ndjensen** [comment]
Your code makes sense to me.  I'm a little concerned if someone wants different behavior though.  For example if they had a `Collection` that implemented `Iterable` and `Iterator`, then they wouldn't get the other methods that wrapping in a `PyJCollection` gets them.  That's purely theoretical though where it sounds like you've actually encountered this being a problem.  I'm trying to think of any other strange scenarios where this could possibly be worse, right now I can't think of any.  I'm curious what @bsteffensmeier thinks.

**Comment by bsteffensmeier** [comment]
I am also slightly bothered by the fact that the change would hide the functionality of PyJIterable but without significantly more work one or the other will not be exposed. As far as I know the current choice is arbitrary so I have no objection to changing it so PyJIterator takes priority. 

For the implementation I would prefer that we just reorder the outer if statement so that `if ((*env)->IsAssignableFrom(env, class, JITERATOR_TYPE))` is moved above `if ((*env)->IsAssignableFrom(env, class, JITERABLE_TYPE)) `. If we can minimize the branching I think the code will be easier to understand and the top if statement provides a linear definition of which interfaces take priority so I would like to keep it that way.

It should theoretically be possible to expose both by using python multiple inheritance to define a class that extends multiple Pyj* classes. I have toyed with code that dynamically defines python types for each java class and I was able to combine types like this so I know it is theoretically possible. Unfortunately it is quite complicated and I have never had the time to get the code fully tested and merged. If we continue to experience these kinds of problems then we will have to work more on something like that.

**Comment by mike-hunhoff** [comment]
Thank you for the feedback, I will open a PR with the proposed changes.

**Comment by bsteffensmeier** [comment]
I think I have it working so we can implement both interfaces, I just submitted #310 with my changes. If I can get that merged we may not need any other changes for your use case.

**Comment by mike-hunhoff** [comment]
@bsteffensmeier wow I love the changes in #310 and I just confirmed this solves my use case (`Python 3.8`, `Ubuntu`). Also, I can't stress enough how helpful it is to have access to the original `Java` type from `Python`, specifically the ability to use `type` and `isinstance.` I can't wait to take advantage of these changes pending a merge!

**Comment by ndjensen** [comment]
@bsteffensmeier, can we close this now that Jep 4.0 is released?
