### ISSUE TITLE
Python objects should not fallback to using str() to convert to Java objects

### ISSUE THREAD

**Issue by ndjensen** [ninia/jep#43]
`pyembed_box_py` in pyembed.c attempts to autobox a Python object into a Java object.  This is most frequently used by `Jep.getValue(String)` but is also used in other areas such as calling Java methods from Python.

`pyembed_box_py` currently checks for a variety of common Python types and handles autoboxing them, but if the Python object does not match one of the checked types then it falls back to turning the Python object into a String.  This is not great as the String representation of a Python object is not particularly useful in Java and can even be misleading.

We can partially alleviate this by adding support for more built-in types to `pyembed_box_py`, though we've already got the most common ones covered.  A potential solution for the fall back behavior is to return a Java `jep.PyObject` which contains a reference to the original Python object.  That `jep.PyObject` object may not be particularly useful in Java (at this time) but at the very least it would be the same object as the original and could be passed back into the Python interpreter for later use.

**Comment by bsteffensmeier** [comment]
The biggest problem I see with PyObject right now is the memory management. Currently whenever a PyObject is created is is registered with `Jep.trackObject()` which keeps the object around until the Jep Interpreter is closed. If PyObjects are used more often for long running interpreters this is basically a memory leak of both the java PyObjects and the python object it is representing.

One option to improve the memory management would be to keep only a WeakReference to the PyObject and then decref the python object when the PyObject is garbage collected. The implementation would be a bit complicated so it would be great if someone could come up with something simpler, however it does align the java garbage collector with the python reference count so its the best solution I can see.

Some more minor issues that we should try to improve on:
1. I don't think that we ever "unbox" a PyObject, so if you pass a PyObject back into python you will get a PyJObject wrapping a PyObject wrapping a real python object.
2. It would be good to implement a few of the basic object methods automatically(toString, equals, hashCode). At the very least toString should call into the python str function. If anyone is relying on the current string behavior then implementing toString might make migration easier.
3. Eventually I think we should plan for PyObject to sprout a hierarchy similar to the way PyJObject has, things like a PyDict implementing the Map interface so we can pass Dicts without copying. Not necessarily at the same time but it is something to consider for the future.
4. This might just be me, but I find the name PyObject confusing. PyObject is already used for the c struct for python objects, I find it hard enough to keep track of things in the different language without reusing names. Maybe it should be called JPyObject since it is the inverse of a PyJObject? Or maybe just JepObject?

**Comment by ndjensen** [comment]
1. Good point, I didn't think of that with passing it back in.
2. You're saying implement those methods on jep.PyObject?
3. Jep has a way to implement Java interfaces with Python objects.  I'm not very familiar with that area of code but that's a potential solution.  We could check the type of the PyObject and its slots for what it implements, then (somehow?) dynamically implement java.lang.Iterable, java.util.Collection, java.util.List, java.util.Map, etc.  And/Or we could implement a basic interface of WrappedPythonObject that has a few methods such as you describe in item 2.  I think there should be an interface there instead of just overriding java.lang.Object methods, I could see us wanting to add some method in the future or maybe even something like a getThreadId().  And potentially there could be other implementations that want to do equals() differently, e.g. equals between a java.util.Map and a python dictionary could perhaps return true.  (I don't know if that's actually useful, just brainstorming).
4. I agree.  Every time we say PyObject I think of the CPython one, not the Jep one.  Will break some backwards compatibility so will need a version increase, but the clarification is worth it.  I like JPyObject for the name since it is the inverse.

**Comment by ndjensen** [comment]
I renamed the ticket though did not edit above comments.  Method `pyembed_box_py()` no longer exists though the same behavior exists.

**Comment by ndjensen** [comment]
I have the foundation for this on a 4.0 branch on my fork.  PyObject, PyCallable, PyIterator.  It's unclear how far to take this and how useful to developers it will be.

**Comment by ndjensen** [comment]
This is targeted for 4.0 to return jep.python.PyObject instead of string as the fallback.

**Comment by ndjensen** [comment]
This was fixed in Jep 4.0.
