### ISSUE TITLE
unsupported callable for PyCallable

### ISSUE THREAD

**Issue by jep-learner** [ninia/jep#454]
I am trying to pass a Java method as an argument to `inspect.getfullargspec` function.

The resulting exception is 
```
Exception in thread "main" jep.JepException: <class 'TypeError'>: unsupported callable
        at ... inspect.getfullargspec(inspect.py:1295)
        at ... inspect.getcallargs(inspect.py:1501)
```

The code example:
```
public class JavaCallable {
    public void printFromJava(){
        System.out.println("Hello, World!");
    }
}
```
```
import jep.JepConfig;
import jep.SharedInterpreter;
import jep.python.PyCallable;

public class ExampleApp {
    public static void main(String[] args) {
        JepConfig config = new JepConfig();
        SharedInterpreter interpreter = new SharedInterpreter();
        String callJavaScript =
            "JavaCallable = jep.findClass('JavaCallable')\n" +
            "javaCallable = JavaCallable()";
        interpreter.exec(callJavaScript);
        PyCallable callable = interpreter.getValue("javaCallable.printFromJava", PyCallable.class);
        interpreter.exec("import inspect");
        interpreter.invoke("inspect.getcallargs", callable);
    }
}
```
I am wondering if this is the correct way to pass a Java method as an argument to the Python function. 

Is there a reason for the exception? 

Is it possible to pass a java method to `inspect.getcallargs` as an argument without getting the `TypeError`?

**Environment:**
- Python 3.10
- Java 11
- Jep 4.1.1
- Python packages used: inspect

Thank you!

**Comment by bsteffensmeier** [comment]
> I am wondering if this is the correct way to pass a Java method as an argument to the Python function.

That is an acceptable way to pass a java method as an argument to the Python function. If you don't need the PyCallable in Java it would probably be better to just leave it in python, there is some overhead to copying objects back and forth. For your last few lines this should work the same as what you have but is slightly simpler to me because it does not create a PyCallable:
```java
        interpreter.exec(callJavaScript);
        interpreter.exec("import inspect");
        interpreter.exec("inspect.getcallargs(javaCallable.printFromJava)");
```
> Is there a reason for the exception?

According to the [documentation](https://docs.python.org/3/library/inspect.html#inspect.getcallargs) `inspect.getcallargs` works on a "Python function or method". The reason for the exception is that a java method is not a Python function or method so getcallargs will not work.

> Is it possible to pass a java method to `inspect.getcallargs` as an argument without getting the `TypeError`?

In the current implementation it is not possible.

I have done a little research to see if there is some API or pattern we can follow to allow Java methods to work better with inspect and have not found anything I am confident would work. [This post](https://stackoverflow.com/questions/57653513/how-to-set-signature-for-python-callables-manually) makes me think we may be able to set `__annotations__` or `__signature__` on the java methods to allow them to work but it would require more research and experimentation to figure out if that is something jep could actually do.

**Comment by jep-learner** [comment]
Thank you so much!
