### ISSUE TITLE
Optionally load jep module using a explicit path

### ISSUE THREAD

**Issue by jvstein** [ninia/jep#51]
I have to launch JVMs from a bunch of different contexts and don't necessarily want to have to set `java.library.path` in all of those locations. For simplicity's sake I'd just like to set the location of the jep native module after my application has started. At the moment that means dangerously hacking the `java.library.path` variable via reflection, which is unreliable depending on the security context.

So, it would be nice to be able to load the jep native module using an explicitly defined path, supplied by a system property via `System.load`. If the system property doesn't exist, Jep can still load the module via the `java.library.path` value.

**Comment by bsteffensmeier** [comment]
1. The [java doc on Runtime](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#loadLibrary%28java.lang.String%29) mentions that System.loadLibrary is the "standard strategy" for loading native code. It worries me that we would need to deviate from the standard, what makes us special? Are we special just because the library is installed into the python module? I would like to find any precedence in other open source projects but it doesn't seem to be a widespread problem.
1. I have always wondered if we could make the path lookup automatic. If we know the lib is installed in the python site packages we should be able to lookup PYTHONPATH or PYTHONHOME in the environment and find jep from there. It seems like this would be simpler for people to setup and test because it would be using the same environment as python. I am not sure exactly how we would translate the environment into a load though.

**Comment by jvstein** [comment]
I'm thinking of it purely from a java application perspective where the python environment is configurable or discoverable. The native module is highly dependent on the python environment, so it make sense to require any usable python environment to have a compatible jep module installed. If I rely on java.library.path, then I either need to use a hacky solution or I need to split my application into multiple processes. Neither solution is particularly appealing.

1. JNA has a user-configurable path for their native library ("jna.boot.library.path"). They also embed the native library in their jar, extract it to a temp folder at runtime and then load it. That pattern is currently impossible for anyone packaging jep (and python) into their own all-in-one jar.
2. I'm trying to make the path lookup automatic in my application. I have Py4J code that I want to move over to Jep, and don't want to track down and modify a lot of startup scripts.

**Comment by bsteffensmeier** [comment]
Jep 3.8 includes [smarter library loading](https://github.com/ninia/jep/blob/v3.8.1/release_notes/3.8-notes.rst#smarter-library-loading). It does not take an explicit path, however it allows you to set a python home and the jep library is found within that directory. I believe that should cover the use cases discussed in this issue so I am closing it. If there are ongoing issues for anyone after the 3.8 upgrade please comment and we can reopen it to consider further enhancements.
