### ISSUE TITLE
error when using \n in python script

### ISSUE THREAD

**Issue by githubbbbber** [ninia/jep#554]
**Describe the bug**
When I use \n in python code, it seems to get confused with python's own indent newlines, resulting in an error.

**To Reproduce**
execute the followding code in JEP java.
```
def mainFunction(args):
    test_str = "bar\nfoo"
```
I used interp.eval(codeStr) passing these code to jep, and used interp.invoke("mainFunction", new Object[] {inputs}); execute the python.
jep returned a exception:
jep.JepException:('unterminated string literal...)...

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: linux
- Python Distribution and Version:3.11
- Java Distribution and Version:11
- Jep Version: 4.2

**Additional context**
I tried to replace \n in java env before passing it to python env, such as new_line  = "\n", then concatenate it with other python strings. But I still got errors in some scenarios such as regular expression. How can I use \n avoiding confusion.

**Comment by githubbbbber** [comment]
I tried seperating test_str into like test_str = "bar" + "\n" + "foo"; and replace \n with \\\\n, os the final codeStr in interp.eval(codeStr) is like
```
def mainFunction(args):
    test_str = "bar\nfoo"
```
not like 
```
def mainFunction(args):
    test_str = "bar
foo"
```
But in some scenarios such as test_str.split("\n") in python, it didn't work. The return is not like ["foo", "bar"] but ["foo\nbar"]

**Comment by bsteffensmeier** [comment]
When you use `\n` in a Java string executed as a Python statement then `\n` is converted to the newline character by Java and Python sees 2 improperly formatted lines. It works for me when I use the `\\n` because then the `\n` is processed by python instead of java. In your example it looks like you reverted back to `\n` in split when it should be `\\n`. This is what works for me:

```java
interpreter.exec("test_str = 'one\\ntwo'");
interpreter.exec("print(test_str.split('\\n'))");
```

I admit that is quite confusing, I would recommend avoiding passing complex strings directly to `eval` or `exec` and instead passing the data values using `set` like this:

```java
interpreter.set("test_str", "one\ntwo");
interpreter.set("delim", '\n');
interpreter.exec("print(test_str.split(delim))");
```

It's also worth noting that this problem is not unique to jep, if you attempt to do the same thing using the python interpreter to run the python builtin `exec` function you will get the same errors as shown below:

```python
>>> exec("test_str='one\ntwo'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    test_str='one
             ^
SyntaxError: unterminated string literal (detected at line 1)
>>> exec("test_str='one\\ntwo'")
>>> exec("print(test_str.split('\n'))")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    print(test_str.split('
                         ^
SyntaxError: unterminated string literal (detected at line 1)
>>> exec("print(test_str.split('\\n'))")
['one', 'two']
```
