### ISSUE TITLE
Distribute application for Windows

### ISSUE THREAD

**Issue by seralbdev** [ninia/jep#575]
**Distribute application for Windows**
I am trying to figure out how to distribute an application (packaged as JAR) that has a dependency on the JEP dll and associated files. I have been able to pip-install the JEP module (build process outputting the DLL) for a concrete version of Python (3.13.0) and everything is working OK, but for that I need to install the MS build environment in the target computer

I have observed that I can "extract" the JEP module folder and deploy it to some arbitrary folder in another Windows computer with the same Python version and I can invoke a Python script from the JVM with no issues:
- MainInterpreter.setJepLibrary pointing to jep.dll
- JepConfig.addIncludePaths pointing to jep root folder

![Screenshot From 2024-11-26 21-45-47](https://github.com/user-attachments/assets/a1fdb116-7da3-4ae0-87f5-f70aadd5c74f)

I wonder:
- Is this a distribution option (JAR+JEP folder) ?
- Which of the files are really necessary?
- Is this JEP folder/DLL specific only for a Python version or does the OS matter as well (provided an x64 Windows 10 OS)?

**Environment**
- Windows 10 IoT Enterprise LTSC 21H2
- python-3.13.0-amd64.exe (Downloaded from here https://www.python.org/downloads/windows/)
- openjdk 21.0.5 2024-10-15 LTS
- Jep 4.2.0

Thanks a lot in advance!

**Comment by bsteffensmeier** [comment]
Although I have built Jep in many configurations I have never distributed a precompiled version of Jep so I will answer to the best of my ability but you will likely have to experiment a bit to find what works. I also recommend you look into distributing jep as a wheel. You can build a wheel from the jep source using `python3 setup.py bdist_wheel`, the wheel will include the compiled jep library along with other necessary files and you should be able to install the wheel on other machines using pip. We have considered distributing jep wheels on pypi but the combinatorics of different python versions and different OS versions makes it more effort then we are willing to put in. Since your use case is limited to a rsingle OS and python version it should be straightforward to build and distribute jep wheels yourself.

For your specific questions.

> * Is this a distribution option (JAR+JEP folder) ?

I don't see any reason this won't work.

> * Which of the files are really necessary?

jep/*.py and jep/jep.dll are definetly necessary for using jep. I am not sure what the jep/jep.cp313-win_amd64.* files do, I don't know much about windows builds but I suspect they are left over artifacts from the build so they might not be necessary.

> * Is this JEP folder/DLL specific only for a Python version or does the OS matter as well (provided an x64 Windows 10 OS)?

The Jep dll should work on any x86_64 version of windows. One caveat to keep in mind tis that if you build jep with numpy support then anywhere it is installed will also need to have numpy installed. If you build without numpy support it can be used with or without numpy but the numpy specific conversions in jep will be disabled.

**Comment by seralbdev** [comment]
Many thanks for the fast reply and the good insights you have given in the post
I think this is enough for me to go ahead
Cheers!
