### ISSUE TITLE
Nested Classes Imported with $ in Name

### ISSUE THREAD

**Issue by djbarker** [ninia/jep#96]
Since nested classes and enums are rendered as dollar sign separated in Java, we cannot import specific subclasses into Python. We can import everything from a package (including nested classes & enums) but the dollar sign in their names is retained meaning they must be accessed via their name in a string. 

Here is an example

In Java:
```java
package MyPackage;

public class MyClass {
    public enum MyEnum {
        VALUE1("Val One"),
        VALUE2("Val Two");
        
        private String val;
        
        Test(String val){ this.val = val; }
    }
}
```

In Python:
```python
from MyPackage import *
print(str(globals()['MyClass$MyEnum'].VALUE1))  # prints "Val One"
```
Ideally it would be possible to do `from MyPackage.MyClass import MyEnum` but I have no idea if this is feasible in Python. Failing this, it might be useful to replace any dollar signs with an underscore.

**Comment by bsteffensmeier** [comment]
The recommended way to access nested classes is like this:
```python
from MyPackage import *
print(str(MyClass.MyEnum.VALUE1))  # prints "Val One"
```

I didn't realize that we even imported the name with a dollar sign, we should probably skip that since it is difficult to use.

I don't think we can support `from MyPackage.MyClass import MyEnum` since that would require MyClass to be both a PyJClass and a module object which would be quite messy.

I would be hesitant to replace the dollar sign with an underscore since MyClass_MyEnum is a valid java class name and we wouldn't want naming conflicts.

**Comment by djbarker** [comment]
Interesting, I tried that form yesterday (it's in my history) with no joy, but today it works. I must have changed something. Sorry for the noise. 

Indeed, that's why I thought it might be tough to implement that, but also agree renaming things is fraught with pitfalls. 

I'm happy to close this issue unless you wish to keep it open because of the names imported with dollar signs.

**Comment by bsteffensmeier** [comment]
I just pushed a fix to dev_3.8(4316630) so that dollar sign names won't be imported anymore in the next release.
